config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/my_deliveries', to: 'deliveries#my_deliveries'
  resources :deliveries do
    resources :loadings, only: [:new, :create, :show] do
      member do
        post 'toggle'
      end
    end
  end

  resources :loadings, only: [:destroy] do
    resources :loadingmaterials, only: :create do
      resources :materials
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  belongs_to :user
  has_many :loadings, dependent: :destroy

  validates :startdate, presence: true
  validates :capacity, presence: true
  validates :finished, acceptance: false
end

app/models/loading.rb
class Loading < ApplicationRecord
  has_many :loadingmaterials, dependent: :destroy
  has_many :materials, through: :loadingmaterials

  belongs_to :delivery

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  after_update :update_delivery_finished

  private

  def update_delivery_finished
    delivery = self.delivery
    loading_done = delivery.loadings.map do |loading|
      loading.done
    end
    delivery.finished = loading_done.reduce(:&)
    delivery.save
  end

end

app/models/loadingmaterial.rb
class Loadingmaterial < ApplicationRecord
  belongs_to :loading
  belongs_to :material


end

app/models/material.rb
class Material < ApplicationRecord
  has_many :loadingmaterials, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
    if current_user.function == "driver"
      stored_location_for(resource) || my_deliveries_path
    elsif current_user.function == "manager"
      stored_location_for(resource) || deliveries_path
    else
      stored_location_for(resource)
    end
  end

end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]


  def index
    @deliveries = Delivery.all
  end

  def my_deliveries
    @deliveries = Delivery.where(user_id: current_user).order(:startdate)
  end

  def show
    @loading = Loading.new
    @markers = @delivery.loadings.order("id ASC").geocoded.map do |loading|
      {
        lat: loading.latitude,
        lng: loading.longitude,
        info_marker: render_to_string(partial: "info_marker_deliveries", locals: { loading: loading }),
      }
    end

  end

  def new
    @delivery = Delivery.new
  end

  def create
    @delivery = Delivery.new(delivery_params)
    @delivery.save
    redirect_to deliveries_path
  end

  def edit
  end

  def update
    @delivery.update(delivery_params)
    redirect_to deliveries_path
  end

  def destroy
    @delivery.destroy
    redirect_to deliveries_path
  end

  private

  def delivery_params
    params.require(:delivery).permit(:name, :startdate, :capacity, :user_id)
  end

  def set_delivery
    @delivery = Delivery.find(params[:id])
  end
end

app/controllers/loadingmaterials_controller.rb
class LoadingmaterialsController < ApplicationController

  def new
    @loading = Loading.find(params[:loading_id])
    @loadingmaterial = Loadingmaterial.new
  end

  def create
    @loading = Loading.find(params[:loading_id])
    @loadingmaterial = Loadingmaterial.new(loadingmaterial_params)
    @loadingmaterial.loading = @loading
    @loadingmaterial.save
    redirect_to delivery_loading_path(@loading.delivery_id, @loading)
  end

  private

  def loadingmaterial_params
    params.require(:loadingmaterial).permit(:material_id, :loading_id, :quantity)
  end
end

app/controllers/loadings_controller.rb
class LoadingsController < ApplicationController
  before_action :set_loading, only: [:show, :edit, :update, :destroy, :toggle]

  def index
  @loadings = Loading.all

  end

  def show
    @markers = [{
      lat: @loading.latitude,
      lng: @loading.longitude,
      info_marker: render_to_string(partial: "info_marker", locals: { loading: @loading }),
    }]
    @loadingmaterial = Loadingmaterial.new
  end

  def new
    @delivery = Delivery.find(params[:delivery_id])
    @loading = Loading.new
  end

  def create
    @loading = Loading.new(loading_params)
    @delivery = Delivery.find(params[:delivery_id])
    @loading.delivery_id = @delivery.id
    redirect_to delivery_path(@loading.delivery_id)
  end

  def edit
  end

  def update
    @loading.update(loading_params)
    redirect_to loading_path(@loading)
  end

  def destroy
    @loading.destroy
    redirect_to delivery_path(@loading.delivery_id)
  end

  def toggle
    @loading.toggle(:done)
    @loading.save
  end

  private

  def loading_params
    params.require(:loading).permit(:name, :address, :date)
  end

  def set_loading
    @loading = Loading.find(params[:id])
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  def index
    @materials = Material.all
  end

  def show
  end

  def new
    @loading = Loading.find(params[:loading_id])
    @material = Material.new
  end

  def create
    @loading = Loading.find(params[:loading_id])
    @material = Material.new(material_params)
    @material.loading = @loading
    if @material.save
      redirect_to loading_path(@loading)
    else
      render 'loadings/show'
    end
  end

  def edit
  end

  def update
    @material.update(material_params)
    redirect_to material_path(@material)
  end

  def destroy
    @material.destroy
    redirect_to materials_path
  end

  private

  def material_params
    params.require(:material).permit(:name, :quantity)
  end

  def set_material
    @material = material.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deliveries/_info_marker_deliveries.erb
<p><strong><%= loading.name %></strong></p>
<p><%= loading.address.split(', ').last %></p>

app/views/deliveries/_load-progress.html.erb
<div class="bar-loading">
  <% sum = 0 %>
    <% Loadingmaterial.where("loading_id <= #{loading.id}").and(Loadingmaterial.where(loading: Loading.where(delivery_id: loading.delivery))).each do |lm| %>
    <% sum = sum + lm.quantity %>
    <% end %>
  <div class="progress">
    <div class="progress-bar " role="progressbar" style="width: <%= (sum.to_f/33*100).round %>%;" aria-valuenow="<%= sum %>" aria-valuemin="0" aria-valuemax="33"></div>
  </div>
  <div id="icon">
  <%= link_to delivery_loading_path(@delivery, loading) do %>
    <%= icon('fa-solid', 'truck') %>
  <% end %>
  </div>
</div>

app/views/deliveries/index.html.erb
<div class="head_deliveries">
    <h1>All deliveries :</h1>
</div>
<div class="container py-4">
      <div class="cards">
        <% @deliveries.order('startdate asc').each do |delivery| %>
            <div class="card-delivery">
              <div class="card-delivery-infos">
                <h2><%= delivery.name %></h2>
                <p><%= delivery.startdate.strftime("%d/%m/%Y") %></p>
                <% if delivery.finished? %>
                <p><%= icon('fa-solid', 'circle-check') %></p>
                <% else %>
                <p><%= icon('fa-solid', 'circle-xmark') %></p>
                <% end %>
              </div>
              <div class="card-delivery-button">
                <h3><%= icon('fa-solid', 'user') %><%=delivery.user.name %></h3>
                <%= link_to "Delivery details", delivery_path(delivery), class: "btn btn-gradient" %>
              </div>
            </div>
        <% end %>
      <% if current_user.function == "manager" %>
        <%= link_to "New Delivery", new_delivery_path(@delivery), class: "btn btn-gradient" %>
      <% end %>

  </div>
</div>

app/views/deliveries/my_deliveries.html.erb
<div class="head_deliveries">
    <h1>your next delivery :</h1>
</div>
<div class="container py-4">
      <div class="cards">
        <% @deliveries.each do |delivery| %>
            <div class="card-delivery">
              <div class="card-delivery-infos">
                <h2>
                  <% if delivery.finished? %>
                    <%= icon('fa-solid', 'circle-check') %>
                  <% else %>
                    <%= icon('fa-solid', 'circle-xmark') %>
                  <% end %>
                  <%= delivery.name %>
                </h2>
                <p><%= delivery.startdate.strftime("%d/%m/%Y") %></p>
              </div>
                <%= link_to "Start delivery", delivery_path(delivery), class: "btn btn-gradient" %>
            </div>
        <% end %>
  </div>
</div>

app/views/deliveries/new.html.erb
<div class="head_deliveries">
  <% if current_user.function == "manager" %>
    <%= link_to deliveries_path do %>
      <%= icon('fa-solid', 'angles-left') %>
    <% end %>
  <% else %>
    <%= link_to my_deliveries_path do %>
      <%= icon('fa-solid', 'angles-left') %>
    <% end %>
  <% end %>
</div>

<div class="container py-4">
  <div class="cards">
    <div class="card-delivery">
      <div class="card-delivery-infos">
        <h2>New Delivery</h2>
        <%= simple_form_for (@delivery) do |f| %>
          <%= f.input :name , as: :string %>
          <%= f.input :startdate, as: :date, order: [:day, :month, :year], label: 'Enter Start Date'%>
          <%= f.input :capacity , as: :integer, :placeholder => 'Enter the max number of pallet'%>
          <%= f.input :user_id , as: :select, :collection =>  User.all, prompt: "Select Driver", label: "Driver" %>
          <%= f.submit "Create Delivery", class: "btn btn-gradient", style: "margin-top: 16px" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/deliveries/show.html.erb
<div class="head_deliveries">
  <% if current_user.function == "manager" %>
    <%= link_to deliveries_path do %>
      <%= icon('fa-solid', 'angles-left') %>
    <% end %>
  <% else %>
    <%= link_to my_deliveries_path do %>
      <%= icon('fa-solid', 'angles-left') %>
    <% end %>
  <% end %>
  <h1><%= @delivery.name %></h1>
</div>

<ol id="progress">
  <% Loading.where(delivery_id: @delivery).order('id asc').each_with_index do |loading, index| %>
    <% if index == 0 %>
      <% if loading.done? %>
        <% if Loading.where(delivery_id: @delivery).order('id asc')[index+1].done? %>
          <li>
            <div class="node blue"></div>
            <div class="progress-info">
            <div class="divider blue"></div>
            <h3><%= index + 1 %> - <%= loading.name %></h3>
              <div class="quantity-info">
                <p><%= loading.address.split(', ').last %></p>
                <%= render partial: "load-progress", locals: {loading: loading} %>
              </div>
            </div>
          </li>
        <% else %>
          <li>
            <div class="node blue"></div>
            <div class="progress-info">
              <div class="divider grey"></div>
              <h3><%= index + 1 %> - <%= loading.name %></h3>
              <div class="quantity-info">
                <p><%= loading.address.split(', ').last %></p>
                <%= render partial: "load-progress", locals: {loading: loading} %>
              </div>
            </div>
          </li>
        <% end %>
      <% else %>
        <li>
          <div class="node grey"></div>
          <div class="progress-info">
            <div class="divider grey"></div>
            <h3><%= index + 1 %> - <%= loading.name %></h3>
            <div class="quantity-info">
              <p><%= loading.address.split(', ').last %></p>
              <%= render partial: "load-progress", locals: {loading: loading} %>
            </div>
          </div>
        </li>
      <% end %>
    <% elsif index < Loading.where(delivery_id: @delivery).count-1 %>
      <% if loading.done? %>
        <% if Loading.where(delivery_id: @delivery).order('id asc')[index+1].done? %>
        <li><div class="divider blue"></div></li>
        <li>
          <div class="node blue"></div>
          <div class="progress-info">
            <div class="divider blue"></div>
            <h3><%= index + 1 %> - <%= loading.name %></h3>
            <div class="quantity-info">
              <p><%= loading.address.split(', ').last %></p>
              <%= render partial: "load-progress", locals: {loading: loading} %>
            </div>
          </div>
        </li>
        <% else %>
          <li><div class="divider blue"></div></li>
          <li><div class="node blue"></div>
            <div class="progress-info">
              <div class="divider grey"></div>
              <h3><%= index + 1 %> - <%= loading.name %></h3>
              <div class="quantity-info">
                <p><%= loading.address.split(', ').last %></p>
                <%= render partial: "load-progress", locals: {loading: loading} %>
              </div>
            </div>
          </li>
        <% end %>
      <% else %>
        <li><div class="divider grey"></div></li>
        <li><div class="node grey"></div>
          <div class="progress-info">
            <div class="divider grey"></div>
            <h3><%= index + 1 %> - <%= loading.name %></h3>
            <div class="quantity-info">
              <p><%= loading.address.split(', ').last %></p>
              <%= render partial: "load-progress", locals: {loading: loading} %>
            </div>
          </div>
        </li>
      <% end %>
    <% elsif index == Loading.where(delivery_id: @delivery).count-1 %>
      <% if loading.done? %>
        <li><div class="divider blue"></div></li>
        <li><div class="node blue"></div>
          <div class="progress-info" style="margin-top:40px">
            <h3><%= index + 1 %> - <%= loading.name %></h3>
            <div class="quantity-info">
              <p><%= loading.address.split(', ').last %></p>
              <%= render partial: "load-progress", locals: {loading: loading} %>
            </div>
          </div>
        </li>
      <% else %>
        <li><div class="divider grey"></div></li>
        <li><div class="node grey"></div>
          <div class="progress-info" style="margin-top:40px">
          <h3><%= index + 1 %> - <%= loading.name %></h3>
            <div class="quantity-info">
              <p><%= loading.address.split(', ').last %></p>
              <%= render partial: "load-progress", locals: {loading: loading} %>
            </div>
          </div>
        </li>
      <% end %>
    <% end %>
  <% end %>
  <% if current_user.function == "manager" %>
    <%= link_to "Add a Loading", new_delivery_loading_path(@delivery), class: "btn btn-gradient" %>
  <% end %>
</ol>

  <% if Loading.where(delivery_id: @delivery).presence %>
    <div id="map"
        style="width:100%"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Happy Logis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>

  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/navbar' %>
    <% end %>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/loadings/_info_marker.erb
<div class="card-delivery-infos">
  <p><%= loading.address.split(', ').first %></p>
  <p><%= loading.address.split(', ').last %></p>
  <% @loading.loadingmaterials.each do |loadingmaterial| %>
    <p><%if loadingmaterial.quantity > 0 %>
      <%= icon('fa-solid', 'circle-arrow-up') %>
      <strong><%= loadingmaterial.quantity %></strong> pallets of <strong><%= loadingmaterial.material.name %></strong></p>
    <%else %>
      <%= icon('fa-solid', 'circle-arrow-down') %>
      <strong><%=  - loadingmaterial.quantity %></strong> pallets of <strong><%= loadingmaterial.material.name %></strong></p>
    <%end %>
  <% end %>
  <p><%= check_box_tag 'done', @loading.id, @loading.done,
    data: {
      remote: true,
      url: url_for(action: :toggle, id: @loading.id),
      method: "POST"
    } %> Complete
  </p>
</div>

app/views/loadings/index.html.erb
<ul>
  <% @loadings.each do |loading| %>
    <li><%= loading.name %> <%= loading.address %> <%= loading.delivery_id %> <%= loading.id %></li>
  <% end %>
</ul>

app/views/loadings/new.html.erb
<div class="head_deliveries">
  <%= link_to delivery_path(@delivery) do %>
    <%= icon('fa-solid', 'angles-left') %>
  <% end %>
  <h1><%= @delivery.name %></h1>
</div>

<div class="container py-4">
  <div class="cards">
    <div class="card-delivery">
      <div class="card-delivery-infos">
        <h2>New Loading</h2>
        <%= simple_form_for [@delivery, @loading] do |f| %>
          <%= f.input :name, as: :string %>
          <%= f.input :address, as: :string %>
          <%= f.input :date, order: [:day, :month, :year], label: 'Date'%>
          <%= f.submit "Create Loading", class: "btn btn-gradient", style: "margin-top: 16px"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/loadings/show.html.erb
<div class="head_deliveries">
    <%= link_to delivery_path(Delivery.find(@loading.delivery_id)) do %>
      <%= icon('fa-solid', 'angles-left') %>
    <% end %>
    <h1><%= @loading.name %></h1>
</div>

<div class="container py-4">
  <div class="cards">
    <div class="card-delivery" style="margin-bottom: 8px">
      <div class="card-delivery-infos" style= "padding: 8px" >
        <p>
        <%= icon('fa-solid', 'location-dot') %> <%= @loading.address %>
        <% if current_user.function == "driver" %>
            <%= link_to "https://waze.com/ul?q=66%20Acacia%20Avenue&ll=#{@loading.latitude},#{@loading.longitude}&navigate=yes" do %>
              <%= icon('fa-brands', 'waze') %>
            <% end %>
        <% end %>
        </p>
        <% @loading.loadingmaterials.each do |loadingmaterial| %>
          <% if loadingmaterial.quantity > 0 %>
            <p>
              <%= icon('fa-solid', 'circle-arrow-up') %>
              <strong><%= loadingmaterial.quantity %></strong> pallets of <strong><%= loadingmaterial.material.name %></strong>
            </p>
          <%else %>
            <p>
              <%= icon('fa-solid', 'circle-arrow-down') %>
              <strong><%=  - loadingmaterial.quantity %></strong> pallets of <strong><%= loadingmaterial.material.name %></strong>
            </p>
          <%end %>
        <% end %>
            <div class="loading-check form-check form-switch" >
              <%= check_box_tag 'flexSwitchCheckChecked', @loading.id, @loading.done, class:"form-check-input",
                  data: {
                    remote: true,
                    url: url_for(action: :toggle, id: @loading.id),
                    method: "POST"
                  } %>
              <label class="form-check-label" for="flexSwitchCheckChecked">Complete</label>
            </div>
          <div>
        </div>
      </div>
    </div>
          <% if current_user.function == "manager" %>
    <div class="cards">
      <div class="card-delivery" style="margin-bottom: 8px">
        <div class="card-delivery-infos" >
            <p>Material in the Truck</p>
            <% list = [] %>
            <% Loadingmaterial.where("loading_id <= #{@loading.id}").and(Loadingmaterial.where(loading: Loading.where(delivery_id: @loading.delivery))).each do |lm| %>
              <% material = lm.material.name.to_sym %>
              <% list << {"#{material}" => lm.quantity} %>
            <% end %>
            <% sum = Hash.new(0) %>
            <% list.each_with_object(sum) do |hash, sum|%>
              <% hash.each { |key, value| sum[key] += value }%>
            <% end %>
            <% sum.each do |material, value|%>
              <p><strong><%= value %></strong> palettes of <strong><%= material %></strong></p>
            <% end %>
            <p> <strong>Give the driver the materials to load/unload</strong>
            <%= simple_form_for([ @loading, @loadingmaterial ]) do |f| %>
              <%= f.input :material_id, as: :select, collection:  Material.all, prompt: "Select Material" %>
              <%= f.input :quantity, placeholder: 'Enter the number of pallet' %>
              <%= f.submit "Add this instruction to the Loading", class: "btn btn-gradient", style: "margin-top: 16px" %>
            <% end %>
      </div>
    </div>
  </div>
          <% end %>
</div>


<div id="map"
    style="width:100%"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Login</title>
	    <meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
		<!-- Font Awesome -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

		<link rel="stylesheet" type="text/css" href="style.css">
	</head>
	<body>
		<div id="loginContainer">
			<div class="login-form">
				<form action="" method="post">
					<div class="text-center padding-top-100px">
            <%= image_tag "logo.png" %>

					</div>

					<!-- <h1 class="text-center light-green-color margin-bottom-25px">NEAT</h1> -->
					<div class="form-group ">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-user"></i></span>
							<input type="text" name="username" class="form-control" placeholder="username" required="required">
						</div>
					</div>

					<div class="form-group">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-lock"></i></span>
							<input type="password" name="password" class="form-control" placeholder="*********" required="required">
						</div>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-success btn-block">
							<a href="#" class="light-green-color">Sign In</a>
						</button>
					</div>

					<div class="clearfix">
			            <label class="pull-left checkbox-inline white-color"><input type="checkbox"> Remember me</label>
			            <a href="#" class="pull-right text-success light-green-color">Forgot Password?</a>
			        </div>

				</form>
				<div class="hint-text">Don't have an account? <a href="new_user_registration_path" class="text-success light-green-color">Register Now!</a></div>
			</div>

		</div>



		<!-- jQuery and Bootstrap JS -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	</body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="flash flash-success alert alert-dismissible fade show" role="alert">
    <span><%= notice %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>
<% if alert %>
  <div class="flash flash-danger alert alert-dismissible fade show" role="alert">
    <span><%= alert %></span>
    <a data-bs-dismiss="alert" aria-label="Close">
      <i class="fas fa-times"></i>
    </a>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <%= image_tag "logo-small.png" %>
    </a>
    <% if user_signed_in? %>
    <div class="nav-item dropdown">
    <%= icon('fa-regular', 'user', data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
    <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
      <% if current_user.function == "manager" %>
        <%= link_to "All deliveries", deliveries_path, class: "dropdown-item" %>
      <% else %>
        <%= link_to "My deliveries", my_deliveries_path, class: "dropdown-item" %>
      <% end %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link"%>
    </div>
  </div>
    <% end %>
  </div>
</div>